services:
  client:
    build: ./client/
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - auth_api
      - id_api

  id_api:
    build: 
      dockerfile: Dockerfile
      context: ./ID_microservice_1/
      target: development
    networks:
      - my-network
    volumes:
      - .:/user/src/app
    expose:
      - "50051"

  auth_api:
    build: 
      dockerfile: Dockerfile
      context: ./AUTH_microservice_2/
      target: development
    volumes:
      - .:/user/src/app
    env_file:
      - .env.stage.dev
    networks:
      - my-network
    expose:
      - "50051"
 
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - my-network
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

networks:
  my-network:
volumes:
  docker-nest-postgres:


        